### ISSUE TITLE
Develop on MacOS

### ISSUE THREAD

**Issue by tanhai1207** [shamanec/GADS-devices-provider#16]
Hi Shamanec,
Thanks for public an interesting project.
I have a free mac PC, do you want to remote in and have full rights to use it for development GADS-devices-provider?

**Comment by shamanec** [comment]
Hey, @tanhai1207! Thank you for the proposal but I recently got a Mac so its all good. I have to let you know though that for now I have no plans of supporting macOS because of some Docker limitations there. Some day I might create a provider that works on macOS without containers but for now there is only Linux support :) Let me know if you use the project and any issues you might encounter!

**Comment by tanhai1207** [comment]
Thank you @shamanec! Hope this project goes well :)

**Comment by shamanec** [comment]
@tanhai1207 Currently the provider supports iOS < 17 and Android on Linux, iOS/Android on macOS and Android only on Windows if you are in any way interested :P
